___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1


#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
np.ones(10)

Створити вектор із значеннями від 0 до 10:

In [4]:
np.arange(0,10,1)

Створити матрицю 5 на 5, заповнену нулями:

In [5]:
np.full((5,5),0)

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [11]:
a = np.random.randint(0, 20, 20)
result = np.where(a == 0)
print(a)
print(result)

[17  5  1  2  0  5 12 15 13  1 19 17  8  1  6  3  1  2  2  8]
(array([4]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [16]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))

6.9
5.0
6.17980582219215


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [21]:
x = np.random.random((4,2))
y = np.random.random((2,2))
z = np.matmul(x,y)
print(x)
print(y)
print(z)

[[0.62221109 0.7929203 ]
 [0.83821806 0.11535009]
 [0.38554825 0.70832835]
 [0.10109486 0.15207552]]
[[0.90512864 0.72682377]
 [0.00760045 0.92806573]]
[[0.56920762 1.18811996]
 [0.75957189 0.71628928]
 [0.35435437 0.9376009 ]
 [0.0926597  0.21461422]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [31]:
vector = np.reshape(z, -1)
max_ = np.amax(vector)
min_ = np.amin(vector)
print(vector)
print(max_, min_)

[0.56920762 1.18811996 0.75957189 0.71628928 0.35435437 0.9376009
 0.0926597  0.21461422]
1.188119955337749 0.0926596985439492


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [45]:
print(np.corrcoef(z[0, :],z[1:, :]))

[[ 1. -1.  1.  1.]
 [-1.  1. -1. -1.]
 [ 1. -1.  1.  1.]
 [ 1. -1.  1.  1.]]


Дано матрицю. Знайти ранг матриці:

In [47]:
a1 = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

print(np.linalg.matrix_rank(a1))

3


Знайти визначник матриці:

In [48]:
print(np.linalg.det(a1))

440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [49]:
print(np.linalg.eig(a1))

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
       -4.56760167-3.20389947j]), array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
        -0.31386258+0.47450898j],
       [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
        -0.07049527-0.4090732j ],
       [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
         0.7099444 -0.j        ]]))


Знайдіть число, що найчастіше зустрічається в масиві:

In [54]:
a2 = np.random.randint(0,10,50)
print(a2)

y2 = np.bincount(a2)
maximum = max(y2)
  
for i in range(len(y2)):
    if y2[i] == maximum:
        print(i, end=" ")

[7 1 5 1 4 4 3 4 2 2 1 8 1 7 7 2 7 9 9 3 6 0 0 9 4 9 0 7 3 4 4 2 2 8 5 6 9
 2 3 9 5 6 2 3 7 5 6 7 1 8]
2 7 

Виведіть лише парні числа, що діляться на 5:

In [55]:
print([j for j in a2 if j%2==0 and j%5==0])

[0, 0, 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [64]:
first = np.array([[2, 5], [1, -10]])
inv_first = np.linalg.inv(first)
second = np.array([1, 3])
x_ = np.linalg.inv(first).dot(second)
print(x_)
print(np.allclose(np.dot(first, x_), second))

[ 1.  -0.2]
True
